// =============================================================================
// Milwaukee Annual Pass — DEMO DATA
// -----------------------------------------------------------------------------
// This is illustrative prototype data. Swap these sample listings for real
// participating partners and offers before launch. Every partner card, the
// value counter, and the savings tracker are driven entirely by this file.
//
// Partner shape:
//   id          unique slug (also used as the localStorage redemption key)
//   name        business name
//   category    one of CATEGORIES (excluding "All")
//   emoji       icon shown on the card / map pin
//   description short one-liner
//   address     street address (demo)
//   benefit     the member benefit headline
//   retailValue numeric normal price (drives value math)
//   memberCost  display string for what the member pays
//   savings     numeric dollars saved (drives value counter + tracker)
//   terms       fine print
//   usageLimit  redemption rule
//   featured    surfaces in "Featured This Week"
//   coords      [lat, lng] for the mock map
// =============================================================================

export const MEMBER = {
  name: "Todd S.",
  number: "MKE-2027-04812",
  status: "ACTIVE",
  validThrough: "December 31, 2027",
  since: "2026",
};

export const PRICE = 99;

export const CATEGORIES = [
  "All",
  "Attractions",
  "Food & Drink",
  "Family",
  "Entertainment",
  "Sports",
  "Museums",
  "Experiences",
  "Wellness",
  "Shopping",
  "Seasonal",
];

export const PARTNERS = [
  {
    id: "art-museum",
    name: "Milwaukee Art Museum",
    category: "Museums",
    emoji: "🖼️",
    description: "Lakefront art icon under the Calatrava wings.",
    address: "700 N Art Museum Dr, Milwaukee, WI 53202",
    benefit: "One complimentary general admission",
    retailValue: 27,
    memberCost: "Free",
    savings: 27,
    terms: "Valid for one general admission. Excludes special ticketed exhibitions.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0400, -87.8969],
  },
  {
    id: "public-museum",
    name: "Milwaukee Public Museum",
    category: "Museums",
    emoji: "🦕",
    description: "Natural history, the Streets of Old Milwaukee & more.",
    address: "800 W Wells St, Milwaukee, WI 53233",
    benefit: "Buy one admission, get one free",
    retailValue: 22,
    memberCost: "50% off (BOGO)",
    savings: 22,
    terms: "Second admission of equal or lesser value. Not valid with other offers.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0410, -87.9170],
  },
  {
    id: "harley",
    name: "Harley-Davidson Museum",
    category: "Museums",
    emoji: "🏍️",
    description: "130+ motorcycles and the story of an American legend.",
    address: "400 W Canal St, Milwaukee, WI 53201",
    benefit: "$10 off admission",
    retailValue: 24,
    memberCost: "$14",
    savings: 10,
    terms: "Valid for one general admission ticket.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0300, -87.9155],
  },
  {
    id: "discovery-world",
    name: "Discovery World",
    category: "Attractions",
    emoji: "🔬",
    description: "Science & technology center on the lakefront.",
    address: "500 N Harbor Dr, Milwaukee, WI 53202",
    benefit: "20% off general admission",
    retailValue: 24,
    memberCost: "$19",
    savings: 5,
    terms: "Discount applies to standard general admission.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0286, -87.8968],
  },
  {
    id: "botanical",
    name: "Boerner Botanical Gardens",
    category: "Attractions",
    emoji: "🌷",
    description: "40 acres of formal gardens in Whitnall Park.",
    address: "9400 Boerner Dr, Hales Corners, WI 53130",
    benefit: "Two-for-one admission",
    retailValue: 14,
    memberCost: "BOGO",
    savings: 14,
    terms: "Second admission of equal or lesser value.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [42.9640, -87.9880],
  },
  {
    id: "pabst-mansion",
    name: "Pabst Mansion Tour",
    category: "Attractions",
    emoji: "🏰",
    description: "Gilded-age brewing-baron mansion, guided tours daily.",
    address: "2000 W Wisconsin Ave, Milwaukee, WI 53233",
    benefit: "Two-for-one guided tour",
    retailValue: 22,
    memberCost: "BOGO tour",
    savings: 22,
    terms: "Second tour ticket of equal or lesser value.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0400, -87.9300],
  },
  {
    id: "zoo",
    name: "Milwaukee County Zoo",
    category: "Family",
    emoji: "🦓",
    description: "One of the country's most popular family zoos.",
    address: "10001 W Bluemound Rd, Milwaukee, WI 53226",
    benefit: "One complimentary child admission",
    retailValue: 17,
    memberCost: "Free child",
    savings: 17,
    terms: "One child admission with a paid adult admission.",
    usageLimit: "One redemption per membership year.",
    featured: true,
    coords: [43.0272, -88.0424],
  },
  {
    id: "kids-zone",
    name: "Kids Discovery Zone",
    category: "Family",
    emoji: "🧸",
    description: "Hands-on indoor play & learning for little ones.",
    address: "929 E Wisconsin Ave, Milwaukee, WI 53202",
    benefit: "One complimentary child admission",
    retailValue: 14,
    memberCost: "Free child",
    savings: 14,
    terms: "One child admission per visit.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0470, -87.9210],
  },
  {
    id: "lakefront-brewery",
    name: "Lakefront Brewery",
    category: "Food & Drink",
    emoji: "🍺",
    description: "Riverfront brewery, tours, and a legendary fish fry.",
    address: "1872 N Commerce St, Milwaukee, WI 53212",
    benefit: "Buy one beer flight, get one free",
    retailValue: 12,
    memberCost: "BOGO flight",
    savings: 12,
    terms: "Must be 21+. Second flight of equal or lesser value.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0530, -87.9080],
  },
  {
    id: "lakefront-social",
    name: "Lakefront Social",
    category: "Food & Drink",
    emoji: "🍽️",
    description: "Elevated neighborhood dining with lake views.",
    address: "1200 E Brady St, Milwaukee, WI 53202",
    benefit: "Complimentary appetizer with entrée purchase",
    retailValue: 14,
    memberCost: "Free appetizer",
    savings: 14,
    terms: "One appetizer per table with purchase of an entrée.",
    usageLimit: "One redemption per membership year.",
    featured: true,
    coords: [43.0100, -87.9110],
  },
  {
    id: "brew-city-coffee",
    name: "Brew City Coffee Co.",
    category: "Food & Drink",
    emoji: "☕",
    description: "Small-batch roaster & cozy neighborhood café.",
    address: "2301 S Kinnickinnic Ave, Milwaukee, WI 53207",
    benefit: "One complimentary specialty drink",
    retailValue: 6,
    memberCost: "Free drink",
    savings: 6,
    terms: "Any specialty espresso drink, up to $6 value.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0100, -87.9060],
  },
  {
    id: "public-market",
    name: "Milwaukee Public Market",
    category: "Food & Drink",
    emoji: "🛍️",
    description: "Historic Third Ward food hall & local vendors.",
    address: "400 N Water St, Milwaukee, WI 53202",
    benefit: "$10 dining credit",
    retailValue: 10,
    memberCost: "$10 credit",
    savings: 10,
    terms: "Valid at participating market vendors.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0339, -87.9075],
  },
  {
    id: "fairway-social",
    name: "Fairway Golf Simulator",
    category: "Experiences",
    emoji: "⛳",
    description: "Indoor golf bays, food, and full bar.",
    address: "1500 N Water St, Milwaukee, WI 53202",
    benefit: "One complimentary hour of simulator time",
    retailValue: 60,
    memberCost: "Free hour",
    savings: 60,
    terms: "One bay, up to four players, subject to availability.",
    usageLimit: "One redemption per membership year.",
    featured: true,
    coords: [43.0180, -87.9200],
  },
  {
    id: "river-cruise",
    name: "Milwaukee Riverwalk Boat Tour",
    category: "Experiences",
    emoji: "🚤",
    description: "Guided sightseeing cruise along the river & harbor.",
    address: "205 W Highland Ave, Milwaukee, WI 53203",
    benefit: "25% off one sightseeing cruise",
    retailValue: 30,
    memberCost: "$22",
    savings: 8,
    terms: "Seasonal. Reservations recommended.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0330, -87.9110],
  },
  {
    id: "axe-mke",
    name: "AXE MKE Throwing Co.",
    category: "Entertainment",
    emoji: "🪓",
    description: "Coached axe-throwing lanes & leagues.",
    address: "1200 S 1st St, Milwaukee, WI 53204",
    benefit: "50% off one session",
    retailValue: 40,
    memberCost: "$20",
    savings: 20,
    terms: "One session per membership. Ages 15+.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0000, -87.9090],
  },
  {
    id: "escape-mke",
    name: "Escape Room MKE",
    category: "Entertainment",
    emoji: "🔐",
    description: "Immersive 60-minute themed escape challenges.",
    address: "324 E Wisconsin Ave, Milwaukee, WI 53202",
    benefit: "20% off one booking",
    retailValue: 32,
    memberCost: "$26",
    savings: 6,
    terms: "Applies to one room booking. Reservation required.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0388, -87.9100],
  },
  {
    id: "bay-view-bowl",
    name: "Bay View Bowl",
    category: "Entertainment",
    emoji: "🎳",
    description: "Classic neighborhood lanes & taproom.",
    address: "2416 S Kinnickinnic Ave, Milwaukee, WI 53207",
    benefit: "One complimentary game",
    retailValue: 8,
    memberCost: "Free game",
    savings: 8,
    terms: "Shoe rental not included. Subject to lane availability.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0000, -87.9060],
  },
  {
    id: "rep-theater",
    name: "Milwaukee Rep Theater",
    category: "Entertainment",
    emoji: "🎭",
    description: "The city's flagship professional theater company.",
    address: "108 E Wells St, Milwaukee, WI 53202",
    benefit: "Two complimentary preview tickets",
    retailValue: 80,
    memberCost: "Free (2 tix)",
    savings: 80,
    terms: "Preview performances only, subject to availability.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0356, -87.9090],
  },
  {
    id: "comedy",
    name: "Downtown Comedy Club",
    category: "Entertainment",
    emoji: "🎤",
    description: "Stand-up, improv & touring headliners.",
    address: "615 E Brady St, Milwaukee, WI 53202",
    benefit: "Two-for-one show tickets",
    retailValue: 24,
    memberCost: "BOGO tickets",
    savings: 24,
    terms: "Select shows. Two-drink minimum may apply.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0370, -87.9080],
  },
  {
    id: "admirals",
    name: "Milwaukee Admirals Hockey",
    category: "Sports",
    emoji: "🏒",
    description: "Fast, family-friendly pro hockey downtown.",
    address: "500 W Kilbourn Ave, Milwaukee, WI 53203",
    benefit: "Buy one ticket, get one free",
    retailValue: 30,
    memberCost: "BOGO ticket",
    savings: 30,
    terms: "Select regular-season home games, subject to availability.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0450, -87.9170],
  },
  {
    id: "wave",
    name: "Milwaukee Wave Indoor Soccer",
    category: "Sports",
    emoji: "⚽",
    description: "The longest-running pro soccer franchise in the U.S.",
    address: "500 W Kilbourn Ave, Milwaukee, WI 53203",
    benefit: "Buy one ticket, get one free",
    retailValue: 28,
    memberCost: "BOGO ticket",
    savings: 28,
    terms: "Select home matches, subject to availability.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0430, -87.9160],
  },
  {
    id: "float-sauna",
    name: "MKE Float & Sauna",
    category: "Wellness",
    emoji: "🧖",
    description: "Sensory-deprivation float tanks & infrared sauna.",
    address: "2210 N Farwell Ave, Milwaukee, WI 53202",
    benefit: "Complimentary introductory float session",
    retailValue: 35,
    memberCost: "Free intro",
    savings: 35,
    terms: "First-time guests. One session per membership.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0230, -87.9130],
  },
  {
    id: "spa",
    name: "Serenity Day Spa",
    category: "Wellness",
    emoji: "💆",
    description: "Massage, facials & full-service day spa.",
    address: "161 W Wisconsin Ave, Milwaukee, WI 53203",
    benefit: "30% off any spa service",
    retailValue: 107,
    memberCost: "30% off",
    savings: 32,
    terms: "One service per membership. Gratuity not included.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0250, -87.9200],
  },
  {
    id: "third-ward-goods",
    name: "Third Ward Goods",
    category: "Shopping",
    emoji: "🛒",
    description: "Curated local makers & lifestyle boutique.",
    address: "219 N Milwaukee St, Milwaukee, WI 53202",
    benefit: "15% off one purchase",
    retailValue: 15,
    memberCost: "15% off",
    savings: 15,
    terms: "Up to $15 value. Excludes gift cards.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0330, -87.9070],
  },
  {
    id: "boswell-books",
    name: "Boswell Book Company",
    category: "Shopping",
    emoji: "📚",
    description: "Beloved independent East Side bookstore.",
    address: "2559 N Downer Ave, Milwaukee, WI 53211",
    benefit: "15% off one purchase",
    retailValue: 15,
    memberCost: "15% off",
    savings: 15,
    terms: "Up to $15 value. Excludes gift cards & events.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0700, -87.8870],
  },
  {
    id: "slice-of-ice",
    name: "Slice of Ice Skating",
    category: "Seasonal",
    emoji: "⛸️",
    description: "Downtown outdoor rink, winter season.",
    address: "920 N Water St, Milwaukee, WI 53202",
    benefit: "Complimentary skate rental",
    retailValue: 12,
    memberCost: "Free rental",
    savings: 12,
    terms: "Seasonal (winter). One rental per membership.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0389, -87.9065],
  },
  {
    id: "holiday-trolley",
    name: "Holiday Lights Trolley",
    category: "Seasonal",
    emoji: "🎄",
    description: "Guided evening tour of the city's holiday lights.",
    address: "Cathedral Square, Milwaukee, WI 53202",
    benefit: "Two-for-one trolley tour",
    retailValue: 18,
    memberCost: "BOGO tour",
    savings: 18,
    terms: "Seasonal (Nov–Dec). Reservation required.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0400, -87.9030],
  },
];

// Benefits pre-redeemed on a member's first visit, so the demo feels "lived-in"
// (these cards show REDEEMED and seed the savings tracker). Days-ago values give
// the "redeemed X days ago" relative timestamps.
export const SEED_REDEMPTIONS = [
  { id: "art-museum", daysAgo: 34 },
  { id: "lakefront-brewery", daysAgo: 12 },
  { id: "brew-city-coffee", daysAgo: 5 },
  { id: "harley", daysAgo: 2 },
];

export const FEATURED = [
  {
    tag: "Milwaukee Weekend Pick",
    ribbon: "Annual Pass Exclusive",
    partnerId: "lakefront-social",
  },
  {
    tag: "Family Pick",
    ribbon: "Annual Pass Exclusive",
    partnerId: "zoo",
  },
  {
    tag: "Experience Pick",
    ribbon: "Annual Pass Exclusive",
    partnerId: "fairway-social",
  },
];

// Mock analytics for the partner-facing dashboard.
export const PARTNER_DASHBOARD = {
  name: "Lakefront Social",
  tag: "Demo Partner",
  offer: "Complimentary appetizer with entrée purchase",
  stats: [
    { label: "Redemptions", value: "183", trend: "+18% MoM" },
    { label: "Est. new customers", value: "146", trend: "+22% MoM" },
    { label: "Offer views", value: "4,827", trend: "+9% MoM" },
    { label: "Profile views", value: "6,102", trend: "+11% MoM" },
    { label: "Est. customer spend", value: "$8,940", trend: "attributed" },
    { label: "Savings provided", value: "$1,647", trend: "to members" },
  ],
  // Monthly redemptions for the mini bar chart.
  monthly: [
    { m: "Apr", v: 18 },
    { m: "May", v: 24 },
    { m: "Jun", v: 29 },
    { m: "Jul", v: 33 },
    { m: "Aug", v: 38 },
    { m: "Sep", v: 41 },
  ],
};

// Real Discover Milwaukee audience reach (as presented in partner proposals).
export const AUDIENCE = [
  { v: "37.1M", l: "Views in 2025" },
  { v: "235K+", l: "Followers" },
  { v: "79.2%", l: "Aged 18–44" },
  { v: "100%", l: "Organic reach" },
];

// Why it's risk-free for a business to join (free-to-join model).
export const PARTNER_ASSURANCES = [
  { emoji: "🆓", title: "$0 to join", desc: "No membership fee and no upfront ad spend. Listing your business and your offer is completely free." },
  { emoji: "🔌", title: "No POS integration", desc: "Nothing to install or connect. Members simply show a redemption screen at the counter." },
  { emoji: "🎯", title: "You only give a perk to real visitors", desc: "The offer happens in person, when a member actually walks in — never to no-shows or bots." },
  { emoji: "🚪", title: "Change or pause anytime", desc: "You control your offer and can update or step away whenever you like. No contracts." },
];

// The "how you actually win" value flow.
export const VALUE_FLOW = [
  { emoji: "🎟️", step: "You post a perk", detail: "e.g. a free appetizer with an entrée" },
  { emoji: "🧭", step: "A member discovers you", detail: "inside a Pass locals open again and again" },
  { emoji: "👥", step: "They visit — and bring a friend", detail: "the friend pays full price" },
  { emoji: "🔁", step: "They come back as a regular", detail: "at full price, again and again" },
];

// Illustrative comparison vs. other local marketing.
export const PARTNER_COMPARISON = {
  columns: ["Annual Pass", "Social ads", "Daily-deal sites", "Print / radio"],
  rows: [
    { label: "Cost to start", vals: ["Free", "Paid", "Free", "$$$"] },
    { label: "Built-in local audience", vals: [true, false, "some", false] },
    { label: "Reaches 235K+ engaged locals", vals: [true, "if you pay", false, false] },
    { label: "Keeps regulars at full price", vals: [true, "n/a", false, "n/a"] },
    { label: "No deep 50%+ discounts", vals: [true, true, false, true] },
    { label: "Trackable redemptions", vals: [true, "impressions only", true, false] },
  ],
};

// Illustrative partner testimonials (sample voices — not real quotes).
export const PARTNER_TESTIMONIALS = [
  { quote: "Pass members find us, try us, and half of them are back within a month — paying full price.", name: "Maria L.", business: "Bay View café", emoji: "☕" },
  { quote: "It costs us nothing to be in it, and it fills our slow weeknights with brand-new faces.", name: "Devin R.", business: "Third Ward restaurant", emoji: "🍽️" },
  { quote: "Finally — marketing where I can actually see how many people walked through the door.", name: "Sam & Kate", business: "Walker's Point experience", emoji: "🎯" },
];

export const PARTNER_FAQ = [
  { q: "What does it cost my business to join?", a: "Nothing. Listing your business and your offer in the Pass is completely free — Discover Milwaukee is funded by the members who buy the $99 annual pass, not by partners." },
  { q: "Will this cannibalize my regular sales?", a: "No. The perk is designed to pull in new customers and fill slower times. Members typically bring full-paying friends and return at full price once they've discovered you." },
  { q: "Do I need special equipment or a POS integration?", a: "No. There's nothing to install. When a member redeems, they show a confirmation screen at the counter — that's the whole process." },
  { q: "Can I change or pause my offer?", a: "Anytime. You're fully in control of your perk and can update or pause it whenever you like. There are no contracts." },
  { q: "How do I know it's working?", a: "Your partner dashboard shows redemptions, estimated new customers, offer views, and attributed spend — so you can see exactly what the Pass is driving." },
  { q: "Are partner spots limited?", a: "Yes. To keep each partner front-and-center, we cap how many businesses we feature per category. Early partners lock in the best visibility." },
];

export const PARTNER_BENEFITS = [
  { emoji: "📣", title: "Reach an engaged audience", desc: "Get in front of Discover Milwaukee's local followers actively planning where to go." },
  { emoji: "🎟️", title: "Placement inside the Pass", desc: "A featured spot in a membership locals open again and again." },
  { emoji: "📊", title: "Trackable redemptions", desc: "See exactly how many members redeemed your offer — no guesswork." },
  { emoji: "🧲", title: "New customer acquisition", desc: "Turn a first-time perk into repeat, full-price visits." },
  { emoji: "🌟", title: "Featured partner promotion", desc: "Editorial features across Discover Milwaukee's channels." },
  { emoji: "🛠️", title: "Simple offer management", desc: "Update or pause your offer anytime. No complicated setup." },
  { emoji: "🧾", title: "No POS integration", desc: "Nothing to install. Members simply show their redemption screen." },
  { emoji: "🔁", title: "Repeat exposure", desc: "Members associate your business with trusted local recommendations." },
];
