// =============================================================================
// Milwaukee Annual Pass -- DEMO DATA
// -----------------------------------------------------------------------------
// This is illustrative prototype data. All partner businesses below are
// FICTIONAL, invented for this demo -- there are no signed partners yet.
// Swap these sample listings for real participating partners and offers once
// they come on board. Every partner card, the value counter, and the savings
// tracker are driven entirely by this file.
//
// Partner shape:
//   id          unique slug (also used as the localStorage redemption key)
//   name        business name (fictional)
//   category    one of CATEGORIES (excluding "All")
//   description short one-liner
//   address     neighborhood (demo)
//   benefit     the member benefit headline
//   retailValue numeric normal price (drives value math)
//   memberCost  display string for what the member pays
//   savings     numeric dollars saved (drives value counter + tracker)
//   terms       fine print
//   usageLimit  redemption rule
//   featured    surfaces in "Featured This Week"
//   coords      [lat, lng] for the mock map
// =============================================================================

export const MEMBER = {
  name: "Todd S.",
  number: "MKE-2027-04812",
  status: "ACTIVE",
  validThrough: "December 31, 2027",
  since: "2026",
};

export const PRICE = 99;

export const CATEGORIES = [
  "All",
  "Attractions",
  "Food & Drink",
  "Family",
  "Entertainment",
  "Sports",
  "Museums",
  "Experiences",
  "Wellness",
  "Shopping",
  "Seasonal",
];

export const PARTNERS = [
  {
    id: "lakeside-gallery",
    name: "Lakeside Art Gallery",
    category: "Museums",
    description: "A lakefront gallery of modern and classic works.",
    address: "Lakefront, Milwaukee",
    benefit: "One complimentary general admission",
    retailValue: 27,
    memberCost: "Free",
    savings: 27,
    terms: "Valid for one general admission. Excludes special ticketed exhibitions.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0400, -87.8969],
  },
  {
    id: "cream-city-history",
    name: "Cream City History Museum",
    category: "Museums",
    description: "Natural history and the story of old Milwaukee.",
    address: "Downtown, Milwaukee",
    benefit: "Buy one admission, get one free",
    retailValue: 22,
    memberCost: "50% off (BOGO)",
    savings: 22,
    terms: "Second admission of equal or lesser value. Not valid with other offers.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0410, -87.9170],
  },
  {
    id: "ironworks-moto",
    name: "Ironworks Motorcycle Museum",
    category: "Museums",
    description: "A century of American motorcycle craft.",
    address: "Menomonee Valley, Milwaukee",
    benefit: "$10 off admission",
    retailValue: 24,
    memberCost: "$14",
    savings: 10,
    terms: "Valid for one general admission ticket.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0300, -87.9155],
  },
  {
    id: "harborline-science",
    name: "Harborline Science Center",
    category: "Attractions",
    description: "Hands-on science and technology on the lakefront.",
    address: "Lakefront, Milwaukee",
    benefit: "20% off general admission",
    retailValue: 24,
    memberCost: "$19",
    savings: 5,
    terms: "Discount applies to standard general admission.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0286, -87.8968],
  },
  {
    id: "cedar-hollow-gardens",
    name: "Cedar Hollow Botanical Gardens",
    category: "Attractions",
    description: "Formal gardens and rotating seasonal blooms.",
    address: "Hales Corners area",
    benefit: "Two-for-one admission",
    retailValue: 14,
    memberCost: "BOGO",
    savings: 14,
    terms: "Second admission of equal or lesser value.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [42.9640, -87.9880],
  },
  {
    id: "ashford-mansion",
    name: "Ashford Mansion Tours",
    category: "Attractions",
    description: "A gilded-age mansion with daily guided tours.",
    address: "Near West Side, Milwaukee",
    benefit: "Two-for-one guided tour",
    retailValue: 22,
    memberCost: "BOGO tour",
    savings: 22,
    terms: "Second tour ticket of equal or lesser value.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0400, -87.9300],
  },
  {
    id: "wildwood-zoo",
    name: "Wildwood Family Zoo",
    category: "Family",
    description: "One of the region's most-loved family zoos.",
    address: "West Side, Milwaukee",
    benefit: "One complimentary child admission",
    retailValue: 17,
    memberCost: "Free child",
    savings: 17,
    terms: "One child admission with a paid adult admission.",
    usageLimit: "One redemption per membership year.",
    featured: true,
    coords: [43.0272, -88.0424],
  },
  {
    id: "little-explorers",
    name: "Little Explorers Discovery Zone",
    category: "Family",
    description: "Hands-on indoor play and learning for little ones.",
    address: "Downtown, Milwaukee",
    benefit: "One complimentary child admission",
    retailValue: 14,
    memberCost: "Free child",
    savings: 14,
    terms: "One child admission per visit.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0470, -87.9210],
  },
  {
    id: "north-point-brewing",
    name: "North Point Brewing Co.",
    category: "Food & Drink",
    description: "Riverfront brewery with tours and a classic fish fry.",
    address: "Brewers Hill, Milwaukee",
    benefit: "Buy one beer flight, get one free",
    retailValue: 12,
    memberCost: "BOGO flight",
    savings: 12,
    terms: "Must be 21+. Second flight of equal or lesser value.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0530, -87.9080],
  },
  {
    id: "rivergate-kitchen",
    name: "Rivergate Kitchen",
    category: "Food & Drink",
    description: "Elevated neighborhood dining with river views.",
    address: "East Side, Milwaukee",
    benefit: "Complimentary appetizer with entree purchase",
    retailValue: 14,
    memberCost: "Free appetizer",
    savings: 14,
    terms: "One appetizer per table with purchase of an entree.",
    usageLimit: "One redemption per membership year.",
    featured: true,
    coords: [43.0100, -87.9110],
  },
  {
    id: "fourth-street-roasters",
    name: "Fourth Street Coffee Roasters",
    category: "Food & Drink",
    description: "Small-batch roaster and cozy neighborhood cafe.",
    address: "Bay View, Milwaukee",
    benefit: "One complimentary specialty drink",
    retailValue: 6,
    memberCost: "Free drink",
    savings: 6,
    terms: "Any specialty espresso drink, up to $6 value.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0100, -87.9060],
  },
  {
    id: "union-market-hall",
    name: "Union Market Hall",
    category: "Food & Drink",
    description: "A bustling food hall of local vendors.",
    address: "Historic Third Ward, Milwaukee",
    benefit: "$10 dining credit",
    retailValue: 10,
    memberCost: "$10 credit",
    savings: 10,
    terms: "Valid at participating market vendors.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0339, -87.9075],
  },
  {
    id: "greenside-golf",
    name: "Greenside Golf Lounge",
    category: "Experiences",
    description: "Indoor golf simulator bays, food, and a full bar.",
    address: "Downtown, Milwaukee",
    benefit: "One complimentary hour of simulator time",
    retailValue: 60,
    memberCost: "Free hour",
    savings: 60,
    terms: "One bay, up to four players, subject to availability.",
    usageLimit: "One redemption per membership year.",
    featured: true,
    coords: [43.0180, -87.9200],
  },
  {
    id: "riverbend-cruises",
    name: "Riverbend Sightseeing Cruises",
    category: "Experiences",
    description: "Guided sightseeing cruises along the river and harbor.",
    address: "Downtown Riverwalk, Milwaukee",
    benefit: "25% off one sightseeing cruise",
    retailValue: 30,
    memberCost: "$22",
    savings: 8,
    terms: "Seasonal. Reservations recommended.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0330, -87.9110],
  },
  {
    id: "timberline-axe",
    name: "Timberline Axe Co.",
    category: "Entertainment",
    description: "Coached axe-throwing lanes and leagues.",
    address: "Walker's Point, Milwaukee",
    benefit: "50% off one session",
    retailValue: 40,
    memberCost: "$20",
    savings: 20,
    terms: "One session per membership. Ages 15+.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0000, -87.9090],
  },
  {
    id: "cipher-escape",
    name: "Cipher Escape Rooms",
    category: "Entertainment",
    description: "Immersive 60-minute themed escape challenges.",
    address: "Downtown, Milwaukee",
    benefit: "20% off one booking",
    retailValue: 32,
    memberCost: "$26",
    savings: 6,
    terms: "Applies to one room booking. Reservation required.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0388, -87.9100],
  },
  {
    id: "southside-lanes",
    name: "Southside Lanes",
    category: "Entertainment",
    description: "Classic neighborhood lanes and taproom.",
    address: "Bay View, Milwaukee",
    benefit: "One complimentary game",
    retailValue: 8,
    memberCost: "Free game",
    savings: 8,
    terms: "Shoe rental not included. Subject to lane availability.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0000, -87.9060],
  },
  {
    id: "grand-marquee",
    name: "Grand Marquee Theatre",
    category: "Entertainment",
    description: "A flagship professional theater company.",
    address: "Downtown, Milwaukee",
    benefit: "Two complimentary preview tickets",
    retailValue: 80,
    memberCost: "Free (2 tix)",
    savings: 80,
    terms: "Preview performances only, subject to availability.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0356, -87.9090],
  },
  {
    id: "backlot-comedy",
    name: "Backlot Comedy House",
    category: "Entertainment",
    description: "Stand-up, improv, and touring headliners.",
    address: "East Side, Milwaukee",
    benefit: "Two-for-one show tickets",
    retailValue: 24,
    memberCost: "BOGO tickets",
    savings: 24,
    terms: "Select shows. Two-drink minimum may apply.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0370, -87.9080],
  },
  {
    id: "cream-city-ice",
    name: "Cream City Ice",
    category: "Sports",
    description: "Fast, family-friendly pro hockey downtown.",
    address: "Downtown, Milwaukee",
    benefit: "Buy one ticket, get one free",
    retailValue: 30,
    memberCost: "BOGO ticket",
    savings: 30,
    terms: "Select regular-season home games, subject to availability.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0450, -87.9170],
  },
  {
    id: "harbor-city-fc",
    name: "Harbor City FC",
    category: "Sports",
    description: "Pro indoor soccer with a loud home crowd.",
    address: "Downtown, Milwaukee",
    benefit: "Buy one ticket, get one free",
    retailValue: 28,
    memberCost: "BOGO ticket",
    savings: 28,
    terms: "Select home matches, subject to availability.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0430, -87.9160],
  },
  {
    id: "stillwater-float",
    name: "Stillwater Float & Sauna",
    category: "Wellness",
    description: "Sensory-deprivation float tanks and infrared sauna.",
    address: "East Side, Milwaukee",
    benefit: "Complimentary introductory float session",
    retailValue: 35,
    memberCost: "Free intro",
    savings: 35,
    terms: "First-time guests. One session per membership.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0230, -87.9130],
  },
  {
    id: "verdant-spa",
    name: "Verdant Day Spa",
    category: "Wellness",
    description: "Massage, facials, and full-service spa days.",
    address: "Downtown, Milwaukee",
    benefit: "30% off any spa service",
    retailValue: 107,
    memberCost: "30% off",
    savings: 32,
    terms: "One service per membership. Gratuity not included.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0250, -87.9200],
  },
  {
    id: "makers-row",
    name: "Maker's Row Boutique",
    category: "Shopping",
    description: "Curated local makers and lifestyle goods.",
    address: "Historic Third Ward, Milwaukee",
    benefit: "15% off one purchase",
    retailValue: 15,
    memberCost: "15% off",
    savings: 15,
    terms: "Up to $15 value. Excludes gift cards.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0330, -87.9070],
  },
  {
    id: "chapter-verse-books",
    name: "Chapter & Verse Books",
    category: "Shopping",
    description: "A beloved independent neighborhood bookstore.",
    address: "East Side, Milwaukee",
    benefit: "15% off one purchase",
    retailValue: 15,
    memberCost: "15% off",
    savings: 15,
    terms: "Up to $15 value. Excludes gift cards and events.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0700, -87.8870],
  },
  {
    id: "central-green-rink",
    name: "Central Green Ice Rink",
    category: "Seasonal",
    description: "Downtown outdoor skating, winter season.",
    address: "Downtown, Milwaukee",
    benefit: "Complimentary skate rental",
    retailValue: 12,
    memberCost: "Free rental",
    savings: 12,
    terms: "Seasonal (winter). One rental per membership.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0389, -87.9065],
  },
  {
    id: "evergreen-lights-trolley",
    name: "Evergreen Lights Trolley",
    category: "Seasonal",
    description: "Guided evening tour of the city's holiday lights.",
    address: "Downtown, Milwaukee",
    benefit: "Two-for-one trolley tour",
    retailValue: 18,
    memberCost: "BOGO tour",
    savings: 18,
    terms: "Seasonal (Nov-Dec). Reservation required.",
    usageLimit: "One redemption per membership year.",
    featured: false,
    coords: [43.0400, -87.9030],
  },
];

// Benefits pre-redeemed on a member's first visit, so the demo feels "lived-in"
// (these cards show REDEEMED and seed the savings tracker). Days-ago values give
// the "redeemed X days ago" relative timestamps.
export const SEED_REDEMPTIONS = [
  { id: "lakeside-gallery", daysAgo: 34 },
  { id: "north-point-brewing", daysAgo: 12 },
  { id: "fourth-street-roasters", daysAgo: 5 },
  { id: "ironworks-moto", daysAgo: 2 },
];

export const FEATURED = [
  {
    tag: "Milwaukee Weekend Pick",
    ribbon: "Annual Pass Exclusive",
    partnerId: "rivergate-kitchen",
  },
  {
    tag: "Family Pick",
    ribbon: "Annual Pass Exclusive",
    partnerId: "wildwood-zoo",
  },
  {
    tag: "Experience Pick",
    ribbon: "Annual Pass Exclusive",
    partnerId: "greenside-golf",
  },
];

// Mock analytics for the partner-facing dashboard (fictional demo partner).
export const PARTNER_DASHBOARD = {
  name: "Rivergate Kitchen",
  tag: "Sample Partner",
  offer: "Complimentary appetizer with entree purchase",
  stats: [
    { label: "Redemptions", value: "183", trend: "+18% MoM" },
    { label: "Est. new customers", value: "146", trend: "+22% MoM" },
    { label: "Offer views", value: "4,827", trend: "+9% MoM" },
    { label: "Profile views", value: "6,102", trend: "+11% MoM" },
    { label: "Est. customer spend", value: "$8,940", trend: "attributed" },
    { label: "Savings provided", value: "$1,647", trend: "to members" },
  ],
  // Monthly redemptions for the mini bar chart.
  monthly: [
    { m: "Apr", v: 18 },
    { m: "May", v: 24 },
    { m: "Jun", v: 29 },
    { m: "Jul", v: 33 },
    { m: "Aug", v: 38 },
    { m: "Sep", v: 41 },
  ],
};

// Real Discover Milwaukee audience reach (as presented in partner proposals).
export const AUDIENCE = [
  { v: "37.1M", l: "Views in 2025" },
  { v: "235K+", l: "Followers" },
  { v: "79.2%", l: "Aged 18-44" },
  { v: "100%", l: "Organic reach" },
];

// Why it's risk-free for a business to join (free-to-join model).
// `icon` maps to the Icon component in components/MilwaukeePass.js.
export const PARTNER_ASSURANCES = [
  { icon: "dollar", title: "$0 to join", desc: "No membership fee and no upfront ad spend. Listing your business and your offer is completely free." },
  { icon: "plug", title: "No POS integration", desc: "Nothing to install or connect. Members simply show a redemption screen at the counter." },
  { icon: "target", title: "You only give a perk to real visitors", desc: "The offer happens in person, when a member actually walks in -- never to no-shows or bots." },
  { icon: "calendar", title: "A full calendar year live", desc: "Your offer runs for the whole calendar year, so members always know they can count on it -- and your business gets a full year of exposure." },
];

// The "how you actually win" value flow.
export const VALUE_FLOW = [
  { icon: "ticket", step: "You post a perk", detail: "e.g. a free appetizer with an entree" },
  { icon: "compass", step: "A member discovers you", detail: "inside a Pass locals open again and again" },
  { icon: "users", step: "They visit -- and bring a friend", detail: "the friend pays full price" },
  { icon: "refresh", step: "They come back as a regular", detail: "at full price, again and again" },
];

// Illustrative comparison vs. other local marketing.
export const PARTNER_COMPARISON = {
  columns: ["Annual Pass", "Social ads", "Daily-deal sites", "Print / radio"],
  rows: [
    { label: "Cost to start", vals: ["Free", "Paid", "Free", "$$$"] },
    { label: "Built-in local audience", vals: [true, false, "some", false] },
    { label: "Reaches 235K+ engaged locals", vals: [true, "if you pay", false, false] },
    { label: "Keeps regulars at full price", vals: [true, "n/a", false, "n/a"] },
    { label: "No deep 50%+ discounts", vals: [true, true, false, true] },
    { label: "Trackable redemptions", vals: [true, "impressions only", true, false] },
  ],
};

// Illustrative partner testimonials (sample voices -- not real quotes).
export const PARTNER_TESTIMONIALS = [
  { quote: "Pass members find us, try us, and half of them are back within a month -- paying full price.", name: "Maria L.", business: "Bay View cafe owner", initials: "ML" },
  { quote: "It costs us nothing to be in it, and it fills our slow weeknights with brand-new faces.", name: "Devin R.", business: "Third Ward restaurant", initials: "DR" },
  { quote: "Finally -- marketing where I can actually see how many people walked through the door.", name: "Sam & Kate", business: "Walker's Point experience", initials: "SK" },
];

export const PARTNER_FAQ = [
  { q: "What does it cost my business to join?", a: "Nothing. Listing your business and your offer in the Pass is completely free -- Discover Milwaukee is funded by the members who buy the $99 annual pass, not by partners." },
  { q: "Will this cannibalize my regular sales?", a: "No. The perk is designed to pull in new customers and fill slower times. Members typically bring full-paying friends and return at full price once they've discovered you." },
  { q: "Do I need special equipment or a POS integration?", a: "No. There's nothing to install. When a member redeems, they show a confirmation screen at the counter -- that's the whole process." },
  { q: "How long does my offer run?", a: "For the full calendar year. That consistency is the whole point -- members need to trust a perk will be there when they walk in, and your business gets a full year of exposure inside the Pass." },
  { q: "How do I know it's working?", a: "Your partner dashboard shows redemptions, estimated new customers, offer views, and attributed spend -- so you can see exactly what the Pass is driving." },
  { q: "Are partner spots limited?", a: "Yes. To keep each partner front-and-center, we cap how many businesses we feature per category. Early partners lock in the best visibility." },
];

export const PARTNER_BENEFITS = [
  { icon: "speaker", title: "Reach an engaged audience", desc: "Get in front of Discover Milwaukee's local followers actively planning where to go." },
  { icon: "ticket", title: "Placement inside the Pass", desc: "A featured spot in a membership locals open again and again." },
  { icon: "chart", title: "Trackable redemptions", desc: "See exactly how many members redeemed your offer -- no guesswork." },
  { icon: "target", title: "New customer acquisition", desc: "Turn a first-time perk into repeat, full-price visits." },
  { icon: "star", title: "Featured partner promotion", desc: "Editorial features across Discover Milwaukee's channels." },
  { icon: "sliders", title: "Simple to set up", desc: "Set your offer once and it runs the full calendar year. No complicated setup, nothing to manage." },
  { icon: "receipt", title: "No POS integration", desc: "Nothing to install. Members simply show their redemption screen." },
  { icon: "refresh", title: "Repeat exposure", desc: "Members associate your business with trusted local recommendations." },
];
